In [2]:
import numpy as np
import pandas as pd

# Z-test

## One-sample Z-test

In [8]:
df = pd.read_csv('z_test_data/01_one_sample_z_mean.csv')
df.head()

   cup_id  fill_ml
0       1   251.16
1       2   235.02
2       3   256.51
3       4   258.79
4       5   224.09

In [9]:
df.shape

(120, 2)

Population

In [10]:
mean_cup_ml_population = df['fill_ml'].mean()
mean_cup_ml_population

np.float64(246.775)

In [11]:
std_cup_ml_population = df['fill_ml'].std()
std_cup_ml_population

np.float64(9.418983423889003)

Sample

In [13]:
n = 40

cup_fill_sample = df.sample(
    n=n,
    random_state=42
)

cup_fill_sample.head()

    cup_id  fill_ml
44      45   248.90
47      48   250.18
4        5   224.09
55      56   239.83
26      27   253.89

In [14]:
mean_cup_ml_sample = cup_fill_sample['fill_ml'].mean()
mean_cup_ml_sample

np.float64(247.58874999999998)