In [2]:
import numpy as np
import pandas as pd

from scipy.stats import norm

# Z-test

## One-sample Z-test

A coffee-machine manufacturer claims that the machine dispenses an average of `250` ml per cup.                                                          
- population standard deviation(sigma): `12`     
--------------------                                                                                                         
Research Question:
- Is the true average amount dispensed different from 250 ml?
---------------------
Identifying the correct Z-test
- I use One-sample Z-test because, we have one sample, output is numerical and population standard deviation is defined.
- I choose `Two-tailed hypothesis` because the research question asks whether the true mean is different, not specifically greater or smaller.
---------------------
Hypotheses:
- H₀: μ = 250
- Hₐ: μ ≠ 250
--------------------
Significance level 
- α = 0.05
------
Formula:
-  Z = (x̄ - μ) / (σ / √n)

In [3]:
coffee_df = pd.read_csv('z_test_data/01_one_sample_z_mean.csv')
coffee_sample = coffee_df['fill_ml']
coffee_df.head()

   cup_id  fill_ml
0       1   251.16
1       2   235.02
2       3   256.51
3       4   258.79
4       5   224.09

In [4]:
# company claims
coffee_mu_0 = 250
# known population stadard deviation
coffee_sigma = 12
# Significance level
coffee_alpha = 0.05

In [5]:
# smple length
coffee_n = len(coffee_sample)
# Calculate the sample mean
coffee_sample_mean = coffee_sample.mean()
# Calculate the standard error
coffee_standard_error = coffee_sigma / np.sqrt(coffee_n)

print("Coffee Machine Sample size:", coffee_n)
print("Coffee Machine Sample mean:", coffee_sample_mean)
print("Coffee Machine Standard error:", coffee_standard_error)

Coffee Machine Sample size: 120
Coffee Machine Sample mean: 246.775
Coffee Machine Standard error: 1.0954451150103321

In [6]:
# Calculate the observed Z-statistic
coffee_z_observed = (
    coffee_sample_mean - coffee_mu_0
) /coffee_standard_error

print("Coffee machine Sample observed Z-statistic:", coffee_z_observed)

Coffee machine Sample observed Z-statistic: -2.9440087465902627

In [7]:
# Find the critical value(s).
coffee_critical_value = norm.ppf(1 - coffee_alpha / 2)
coffee_lower_critical = -coffee_critical_value
coffee_upper_critical = coffee_critical_value
print("Coffee machine Sample Critical values:",
      coffee_lower_critical,
      coffee_upper_critical)

# Decision using critical values
if coffee_z_observed < coffee_lower_critical or coffee_z_observed > coffee_upper_critical:
    print("Reject H₀ using critical-value method")
else:
    print("Fail to reject H₀ using critical-value method")

Coffee machine Sample Critical values: -1.959963984540054 1.959963984540054
Reject H₀ using critical-value method

In [8]:
# P-value
coffee_p_value = 2 * norm.cdf(coffee_z_observed)
print("Coffee Machine P-value:", coffee_p_value)
print("Coffee Machine Alpha:", coffee_alpha)

# Dicision using p-value
if coffee_p_value < coffee_alpha:
    print("Reject H₀")
else:
    print("Fail to reject H₀")

Coffee Machine P-value: 0.0032399084308324297
Coffee Machine Alpha: 0.05
Reject H₀

at the `5% significance level`, there is sufficient statistical evidence to conclude that the true mean amount dispensed by the coffee machine is different from 250 ml.

## Two-sample Z-test

A company wants to know whether average customer satisfaction differs between Group A and Group B.                                                              
Known population standard deviations:
- sigma_A = `10`
- sigma_B = `12`
-------
Research question:
- Is the population mean satisfaction score different between `Group A` and `Group B`?
-------
Identifying the correct `Z-test`
- I can apply `Two-sample Z-test` because two-numerical samples, known standard deviations and numerical output
- I choose `Two-tailed hypothesis` because the company wants to know whether statisfaction score is different between Group_A and Group_B
------                  
Hypothesis:
- H₀: μ_A = μ_B
- Hₐ: μ_A ≠ μ_B
------
Significance level 
- α = 0.05
------
Formula:
- Z = (X̄_A - X̄_B) / √((σ_A² / n_A) + (σ_B² / n_B))

In [31]:
df_two_sample = pd.read_csv("z_test_data/02_two_sample_z_mean.csv")
df_two_sample.head()

   customer_id group  satisfaction_score
0            1     A               61.77
1            2     A               73.79
2            3     A               74.20
3            4     A               85.59
4            5     A               80.35

In [10]:
df_two_sample['group'].value_counts()

group
A    100
B    100
Name: count, dtype: int64

In [33]:
# sample A 
statisfaction_score_sample_A_std = 10

# sample B 
statisfaction_score_sample_B_std = 12

# Significance level 
statisfaction_score_alpha = 0.05

In [35]:
# sample A 
statisfaction_score_sample_A = df_two_sample[df_two_sample['group'] == 'A']['satisfaction_score']
statisfaction_score_sample_A_n = len(statisfaction_score_sample_A)
statisfaction_score_sample_A_mean = statisfaction_score_sample_A.mean()
print("statisfaction_score_ Sample A mean: ", statisfaction_score_sample_A_mean)

# Sample B
statisfaction_score_sample_B = df_two_sample[df_two_sample['group'] == 'B']['satisfaction_score']
statisfaction_score_sample_B_mean = statisfaction_score_sample_B.mean()
statisfaction_score_sample_B_n = len(statisfaction_score_sample_B)
print("statisfaction_score Sample B mean: ", statisfaction_score_sample_B_mean)

statisfaction_score_ Sample A mean:  71.90969999999999
statisfaction_score Sample B mean:  74.2679

In [36]:
# Two-sample-Z-statistic calculation: Z = (X̄_A - X̄_B) / √((σ_A² / n_A) + (σ_B² / n_B))
statisfaction_score_two_sample_Z_test = (
    (statisfaction_score_sample_A_mean - statisfaction_score_sample_B_mean)
    /
    np.sqrt(
        (statisfaction_score_sample_A_std ** 2 / statisfaction_score_sample_A_n) 
        + 
        (statisfaction_score_sample_B_std ** 2 / statisfaction_score_sample_B_n)
    )
)

print("statisfaction score Test Statistic Value", statisfaction_score_two_sample_Z_test)

statisfaction score Test Statistic Value -1.5096828512887834

In [39]:
# finding critical_value
statisfaction_score_critical_value = norm.ppf(1 - statisfaction_score_alpha / 2)
statisfaction_score_upper_critical = statisfaction_score_critical_value
statisfaction_score_lower_critical = -statisfaction_score_critical_value
print(f"Statisfaction score Upper critical Value: {statisfaction_score_upper_critical}")
print(f"Statisfaction score lower critical Value: {statisfaction_score_lower_critical}")

# making decision by critical values
if (
    statisfaction_score_two_sample_Z_test < statisfaction_score_lower_critical
    or 
    statisfaction_score_two_sample_Z_test > statisfaction_score_upper_critical
):
    print("Reject H₀")
else:
    print("Failed to reject H₀")

Statisfaction score Upper critical Value: 1.959963984540054
Statisfaction score lower critical Value: -1.959963984540054
Failed to reject H₀

at the `5% significance level`, there is not enough statistical evidence to conclude that the population mean satisfaction scores differ between Group A and Group B.

## One-Proportion Z-test

Historically, `30% `of website visitors make a purchase.                                                                                                        
Research Question:
- has the purchase rate increased above 30%?
-------
Indentifying the Correct Z-test
- I can use `Proportion Z-test `because I am  going to test proportion 
- I choose `Right(one)-tailed proportion Z-test`, because the research question asks: has the purchase rate increased ? 
------
Hypotheses:
- H₀: p = 0.30
- Hₐ: p > 0.30

In [84]:
df_one_proportion = pd.read_csv("z_test_data/03_one_proportion_z.csv")
df_one_proportion.head()

   visitor_id  purchased
0           1          1
1           2          1
2           3          0
3           4          0
4           5          0

In [87]:
# population mean purchase rate
purchase_rate_population_p = 0.30

# significance level alpga 
purchase_rate_alpha = 0.05

In [88]:
# sample 
purchase_rate_sample = df_one_proportion['purchased']
# sample length 
purchase_rate_n = len(df_one_proportion)
# sample mean
purchase_rate_sample_p = purchase_rate_sample.sum() / purchase_rate_n

print("purchase rate Sample length: ", purchase_rate_n)
print("purchase rate Sample Mean: ", purchase_rate_sample_p)

purchase rate Sample length:  300
purchase rate Sample Mean:  0.38666666666666666

In [90]:
# observed Z-statistic Z = (p̂ - p₀) / √((p₀(1 - p₀)) / n)
purchase_rate_z_observed = (
    (purchase_rate_sample_p - purchase_rate_population_p) 
    / 
    np.sqrt(
        purchase_rate_population_p 
        * 
        (1 - purchase_rate_population_p)
        / 
        purchase_rate_n
    )
)
print("purchase rate Observed Z-statistc value: ", purchase_rate_z_observed)

purchase rate Observed Z-statistc value:  3.2756920994133027

In [91]:
# critical Value 
purchase_rate_critical_value = norm.ppf(1 - purchase_rate_alpha)
print(f"Purchase Rate Critical Value: {purchase_rate_critical_value}")

# making decision by critical value
if purchase_rate_z_observed > purchase_rate_critical_value:
    print("Reject H₀")
else:
    print("Fail to reject  H₀")

Purchase Rate Critical Value: 1.6448536269514722
Reject H₀

In [93]:
# p-value
purchase_rate_p_value = 1 - norm.cdf(purchase_rate_z_observed)
print(f"Purchase rate P-value: {purchase_rate_p_value}")

# making decision by p-value
if purchase_rate_p_value < purchase_rate_alpha:
    print("Reject H₀")
else:
    print("Fail to reject H₀")

Purchase rate P-value: 0.0005270170228923732
Reject H₀

At the 5% significance level, there is sufficient statistical evidence to conclude that the population purchase rate has increased above 30%

## Two-Proportion Z-test