In [47]:
import pandas as pd
import numpy as np

from scipy.stats import t

# Tests

## One-Sample T-test

A delivery company claims that it's average delivery time `30 minutes`. Population std(σ) is unknown.                                                    
Research questions:
- Is the average delivery time different from 30 minutes
-----
Indentifying the correct Hypothesis test
- I can use `One-Sample T-test` since there is one sample and Standard deviation is unknown
- I choose `Two-tailed One-Sample T-test` because the research questions asked the difference
-----
Hypothesis:
- H₀: μ = 30
- Hₐ: μ ≠ 30
---- 
Significance level α 
- α = 0.05 I accept `5% Type I` error
--- 
Formula:
- t = (X̄ - μ₀) / (s / √n)

In [48]:
delivery_df = pd.read_csv("data/01_one_sample_t_mean.csv")
delivery_df.head()

   delivery_id  delivery_time_min
0            1              31.08
1            2              32.04
2            3              29.47
3            4              31.24
4            5              33.71

In [49]:
# company claims 
delivery_mu_0 = 30
# significance_level alpha
delivery_alpha = 0.05

In [50]:
# sample
delivery_sample = delivery_df['delivery_time_min']
# sample length 
delivery_n = len(delivery_sample)
# degrees of freedom
delivery_df_value = delivery_n - 1
# delivery sample mean 
delivery_mean = np.mean(delivery_sample)
# delivery sample standard deviation
delivery_std = delivery_sample.std()


print(F"Delivery Sample Size: {delivery_n}")
print(F"Delivery Sample Mean: {delivery_mean}")
print(F"Delivery Sample STD: {delivery_std}")

Delivery Sample Size: 40
Delivery Sample Mean: 32.888
Delivery Sample STD: 5.003730505768568

In [51]:
# calculating the One-sample T-test
delivery_t_observed = (
    (delivery_mean - delivery_mu_0) 
    /
    (delivery_std / np.sqrt(delivery_n))
)

print(f"Delivery Sample observed One-Sample T-test Value: {delivery_t_observed}")

Delivery Sample observed One-Sample T-test Value: 3.6503396304168088

In [52]:
# Finding critical values
delivery_critical_values = t.ppf(1 - delivery_alpha / 2, df=delivery_df_value)
delivery_lower_critical = - delivery_critical_values
delivery_upper_critical = delivery_critical_values
print(F"Delivery Lower Critical Value: {delivery_lower_critical}")
print(F"Delivery Upper Critical Value: {delivery_upper_critical}")

# Making decision by critical values
if delivery_t_observed < delivery_lower_critical or delivery_t_observed > delivery_upper_critical:
    print("Reject H₀")
else:
    print("Fail to Reject H₀")

Delivery Lower Critical Value: -2.0226909200367604
Delivery Upper Critical Value: 2.0226909200367604
Reject H₀

In [53]:
# p-value
delivery_p_value = 2  * t.sf(
    abs(delivery_t_observed), 
    df=delivery_df_value
)
print("Delivery p-value: ", delivery_p_value)
print("Delivery Alpha: ", delivery_alpha)

if delivery_p_value < delivery_alpha:
    print("Reject H₀")
else:
    print("Fail to Reject H₀")

Delivery p-value:  0.0007666974254171365
Delivery Alpha:  0.05
Reject H₀

At the `5%` significance level, there is sufficient statistical evidence to conclude that the true average delivery time is `different from 30 minutes`.

## Independent Two-Sample T-test

A company compares employee productivity scores between two independent teams: Group A and Group B.                                                      
Research question:
- Are the population mean productivity scores different between Group A and Group B?
---
Identifying the correct Hypothesis test
- I can use `Independent Two-Sample T-test` since there are two independent group samples and Standard deviations are unknown
- I choose `Two-tailed Independent Two-Sample T-Test` because the reasearch question asked the difference 
--- 
Hypothesis:
- H₀: μ_A = μ_B
- Hₐ: μ_A ≠ μ_B
---
Significance level α
- α = 0.05 I accept 5% Type I error
---
Formula
- t = (X̄_A - X̄_B) / √((s_A² / n_A) + (s_B² / n_B))

In [54]:
employee_scores_df = pd.read_csv('data/02_independent_two_sample_t.csv')
employee_scores_df.head()

   employee_id group  productivity_score
0            1     A               65.18
1            2     A               78.74
2            3     A               74.54
3            4     A               59.86
4            5     A               77.16

In [55]:
# significance level alpha 
employee_scores_alpha = 0.05

In [56]:
# Samples
employee_scores_sample_A = employee_scores_df[employee_scores_df['group'] == 'A']['productivity_score']
employee_scores_sample_B = employee_scores_df[employee_scores_df['group'] == 'B']['productivity_score']

# Samples lengths
employee_scores_sample_A_n = len(employee_scores_sample_A)
employee_scores_sample_B_n = len(employee_scores_sample_B)

# Sample means
employee_scores_sample_A_mean = employee_scores_sample_A.mean()
employee_scores_sample_B_mean = employee_scores_sample_B.mean()

# Samples Standard deviations
employee_scores_sample_A_std = employee_scores_sample_A.std()
employee_scores_sample_B_std = employee_scores_sample_B.std()



print(f"Employee Scores Sample A lenth: {employee_scores_sample_A_n}")
print(f"Employee Scores Sample B lenth: {employee_scores_sample_B_n}")
print(f"Employee Scores Sample A mean: {employee_scores_sample_A_mean}")
print(f"Employee Scores Sample B mean: {employee_scores_sample_B_mean}")
print(f"Employee Scores Sample A standard deviation: {employee_scores_sample_A_std}")
print(f"Employee Scores Sample B standard deviation: {employee_scores_sample_B_std}")

Employee Scores Sample A lenth: 48
Employee Scores Sample B lenth: 52
Employee Scores Sample A mean: 71.75666666666666
Employee Scores Sample B mean: 78.46403846153848
Employee Scores Sample A standard deviation: 8.290239155068264
Employee Scores Sample B standard deviation: 9.4515987359366

In [57]:
employee_scores_df_value = (
    (
        employee_scores_sample_A_std**2 / employee_scores_sample_A_n
        +
        employee_scores_sample_B_std**2 / employee_scores_sample_B_n
    ) ** 2
    /
    (
        (
            employee_scores_sample_A_std**2
            / employee_scores_sample_A_n
        ) ** 2 / (employee_scores_sample_A_n - 1)
        +
        (
            employee_scores_sample_B_std**2
            / employee_scores_sample_B_n
        ) ** 2 / (employee_scores_sample_B_n - 1)
    )
)

In [58]:
# Calculating Independent Two-Samples T-test 
employee_scores_t_observed = (
    (employee_scores_sample_A_mean - employee_scores_sample_B_mean) 
    / 
    np.sqrt(
        (employee_scores_sample_A_std ** 2 / employee_scores_sample_A_n)
        +
        (employee_scores_sample_B_std ** 2 / employee_scores_sample_B_n)
    )
)

print(f"Employee productivity scores samples observed independent two-sample t-test value: {employee_scores_t_observed}")

Employee productivity scores samples observed independent two-sample t-test value: -3.7793128971803616

In [59]:
# Finding critical values
employee_scores_critical_values = t.ppf(1 - employee_scores_alpha / 2, df=employee_scores_df_value)
employee_scores_upper_critical = employee_scores_critical_values
employee_scores_lower_critical = -employee_scores_critical_values

print(f"Employee scores Upper critical value: {employee_scores_upper_critical}")
print(f"Employee scores Lower critical value: {employee_scores_lower_critical}")

# making decision by critical values
if employee_scores_t_observed > employee_scores_upper_critical or employee_scores_t_observed < employee_scores_lower_critical:
    print("Reject H₀")
else:
    print("Fail to Reject H₀")

Employee scores Upper critical value: 1.9845296076421937
Employee scores Lower critical value: -1.9845296076421937
Reject H₀

In [60]:
# P-Value
employee_scores_p_value = 2 * t.sf(
    abs(employee_scores_t_observed),
    df=employee_scores_df_value
)
print(f"Employee scores p-value: {employee_scores_p_value}")
print(f"Employee scores Alpha: {employee_scores_alpha}")

if employee_scores_p_value < employee_scores_alpha:
    print("Reject H₀")
else:
    print("Fail to Reject H₀")

Employee scores p-value: 0.0002705288878007695
Employee scores Alpha: 0.05
Reject H₀

At the `5% significance level`, there is sufficient statistical evidence to conclude that Group A employee productivity scores are different from Group B employees productivity scores

## Paired T-test

The same participants take a skills test before and after a training program.                                                                            
Research Question:
- Has the training increased the average score ?
---
Indentifying the Hypothesis test
- I can use `Paired T-test` since two being compared samples are dependent
- I choose `Right_Tailed Paired T-test` because the research question asked grow
---
Hypothesis:
- H₀: μ = 0
- Hₐ: μ > 0
---
Significance level α
- α = 0.05 I accept 5% Type I error
--- 
Formula:
- t = d̄ / (s_d / √n)

In [61]:
skill_test_df = pd.read_csv("data/03_paired_t.csv")
skill_test_df.head()

   participant_id  score_before  score_after
0               1         63.59        62.16
1               2         68.47        78.99
2               3         62.08        62.49
3               4         77.20        83.28
4               5         56.02        52.01

In [62]:
# Significance level Alpga
skill_test_alpha = 0.05

In [63]:
# Samples
scores_before = skill_test_df['score_before']
scores_after = skill_test_df['score_after']

# differences 
scores_differences = scores_after - scores_before

# differences statistics
differences_mean = scores_differences.mean()
differences_std = scores_differences.std()
differences_n = len(scores_differences)
skill_test_df_value = differences_n - 1

print(f"Score differences mean: {differences_mean}")
print(f"Score differences standard deviation: {differences_std}")
print(f"Score differences length: {differences_n}")

Score differences mean: 2.981428571428572
Score differences standard deviation: 4.004842027329611
Score differences length: 35

In [64]:
# calculating Paired T-test
skill_test_pair_t_observed = differences_mean / (differences_std / np.sqrt(differences_n))
print(f"Test scores Paired T-test observed value: {skill_test_pair_t_observed}")

Test scores Paired T-test observed value: 4.404260936091214

In [65]:
# Finding critical Value 
skill_test_critical_value = t.ppf(1 - skill_test_alpha, df=skill_test_df_value)
print(f"Skill test critical Value: {skill_test_critical_value}")

# making decision by critical value
if skill_test_pair_t_observed > skill_test_critical_value:
    print("Reject H₀")
else:
    print("Fail to Reject H₀")

Skill test critical Value: 1.6909242551868549
Reject H₀

In [67]:
# P-value
skill_test_p_value = t.sf(abs(skill_test_pair_t_observed), df=skill_test_df_value)
print(f"Skill test p-value: {skill_test_p_value}")

if skill_test_p_value < skill_test_alpha:
    print("Reject H₀")
else:
    print("Fail to reject H₀")

Skill test p-value: 5.012018607697337e-05
Reject H₀

At the `5% significance level`, there is no sufficient statistical evidence to conclude that the training program increases the skill test scores