In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("sampling_practice_students.csv")
df.head()

,student_id,registration_order,registration_date,region,city,school_id,department,study_level,gender,age,scholarship,uses_online_platform,study_hours_week,attendance_pct,exam_score,satisfaction_score
0,STU00001,1,2025-09-01,Mazowieckie,Warsaw,SCH001,Data Science,Bachelor,Male,22,No,No,12.8,53.8,64.5,5.0
1,STU00002,2,2025-09-01,Mazowieckie,Warsaw,SCH001,Software Engineering,Master,Male,31,Yes,Yes,23.4,73.9,83.8,9.6
2,STU00003,3,2025-09-01,Mazowieckie,Warsaw,SCH001,Cybersecurity,Master,Female,27,Yes,Yes,18.1,75.5,77.1,7.2
3,STU00004,4,2025-09-01,Mazowieckie,Warsaw,SCH001,Cybersecurity,Bachelor,Female,25,No,No,12.2,71.9,69.4,5.8
4,STU00005,5,2025-09-01,Mazowieckie,Warsaw,SCH001,Data Science,Master,Female,27,No,Yes,8.2,91.1,76.7,7.7

In [3]:
len(df)

2400

## Simple Random Sampling

In [4]:
population_size = len(df)
sample_size = 240

print(f"Population size: {population_size}")
print(f"Sample size: {sample_size}")

Population size: 2400
Sample size: 240

In [13]:
simple_random_sample = df.sample(
    n=sample_size,
    replace=False,
    random_state=42
)

In [14]:
simple_random_sample.head()

,student_id,registration_order,registration_date,region,city,school_id,department,study_level,gender,age,scholarship,uses_online_platform,study_hours_week,attendance_pct,exam_score,satisfaction_score
2037,STU02038,2038,2026-06-19,Malopolskie,Krakow,SCH021,Business Analytics,Master,Male,22,Yes,Yes,19.4,71.5,74.7,5.1
1978,STU01979,1979,2026-06-10,Malopolskie,Krakow,SCH020,Software Engineering,Master,Other/Prefer not to say,33,No,No,16.7,89.3,95.9,7.2
855,STU00856,856,2026-01-01,Slaskie,Katowice,SCH009,Software Engineering,Master,Female,29,No,Yes,8.0,89.0,67.5,7.9
1719,STU01720,1720,2026-05-04,Malopolskie,Krakow,SCH018,Business Analytics,Bachelor,Male,23,No,Yes,12.5,72.9,68.2,6.0
2019,STU02020,2020,2026-06-16,Malopolskie,Krakow,SCH021,Cybersecurity,Master,Male,29,No,Yes,19.0,78.8,91.1,7.2

In [15]:
simple_random_sample.shape

(240, 16)

In [16]:
simple_random_sample["student_id"].duplicated().sum()

np.int64(0)

Comparing **Population** vs **Sample**

In [25]:
num_columns = ['age', 'study_hours_week', 'attendance_pct', 'exam_score', 'satisfaction_score']
print("Population: ")
df[num_columns].describe()

Population:

,age,study_hours_week,attendance_pct,exam_score,satisfaction_score
count,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000
mean,23.745000,15.508250,80.459792,84.421750,7.348875
std,4.793177,5.215315,9.740378,10.918343,1.240248
min,18.000000,2.000000,49.800000,42.700000,3.100000
25%,20.000000,12.000000,73.700000,77.100000,6.500000
50%,23.000000,15.400000,80.500000,85.200000,7.400000
75%,25.000000,18.925000,87.400000,92.900000,8.200000
max,45.000000,38.000000,100.000000,100.000000,10.000000

In [24]:
simple_random_sample[num_columns].describe()

,age,study_hours_week,attendance_pct,exam_score,satisfaction_score
count,240.000000,240.000000,240.000000,240.000000,240.000000
mean,23.700000,14.740000,80.498333,83.411250,7.348333
std,4.391128,4.874353,9.605002,10.928884,1.237996
min,18.000000,2.600000,51.100000,57.500000,4.100000
25%,21.000000,11.525000,73.275000,75.425000,6.375000
50%,23.000000,14.700000,79.850000,84.500000,7.400000
75%,25.000000,18.125000,87.775000,91.800000,8.200000
max,41.000000,29.200000,100.000000,100.000000,10.000000

In [29]:
population_department = (
    df['department'].value_counts(normalize=True).mul(100)
)
sample_depratment = (
    simple_random_sample['department'].value_counts(normalize=True).mul(100)
)
department_comparison = pd.DataFrame({
    "Population Percentage":np.round(population_department,1),
    "Sample Percentage": np.round(sample_depratment,1)
})
department_comparison

                      Population Percentage  Sample Percentage
department
Business Analytics                     15.3               16.2
Cybersecurity                          24.5               24.6
Data Science                           30.0               30.8
Software Engineering                   30.2               28.3

In [30]:
population_region = (
    df['region'].value_counts(normalize=True).mul(100)
)
sample_region = (
    simple_random_sample['region'].value_counts(normalize=True).mul(100)
)
region_comparison = pd.DataFrame({
    "Population Percentage":np.round(population_region,1),
    "Sample Percentage": np.round(sample_region,1)
})
region_comparison

             Population Percentage  Sample Percentage
region
Malopolskie                   30.4               31.2
Mazowieckie                   34.0               29.6
Slaskie                       35.6               39.2

In [31]:
population_gender = (
    df['gender'].value_counts(normalize=True).mul(100)
)
sample_gender = (
    simple_random_sample['gender'].value_counts(normalize=True).mul(100)
)
gender_comparison = pd.DataFrame({
    "Population Percentage":np.round(population_gender,1),
    "Sample Percentage": np.round(sample_gender,1)
})
gender_comparison

                         Population Percentage  Sample Percentage
gender
Female                                    48.6               41.2
Male                                      47.3               53.8
Other/Prefer not to say                    4.1                5.0