In [9]:
import pandas as pd
import numpy as np

In [10]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [11]:
df = pd.read_csv("data/datav3.csv")
df.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

In [15]:
df.shape

(7519, 29)

# Assumptions

## Independence of Observations

### Repeated entities and Duplicated IDs

#### Duplicated IDs

In [12]:
df.duplicated().sum()

np.int64(35)

In [14]:
exact_duplicates = df[df.duplicated(keep=False)]
exact_duplicates.sort_values(['customer_id', 'observation_month'])

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
5077,CUST00501,2025-08-01,B08,33,3078.55,36733.47,4,14,33.36,1.40,2,0,5.8,2,10,2,0,5,13,Mobile,East,Dark,Bachelor,Organic,CMP04,-0.3185,-0.9865,0,0
6080,CUST00501,2025-08-01,B08,33,3078.55,36733.47,4,14,33.36,1.40,2,0,5.8,2,10,2,0,5,13,Mobile,East,Dark,Bachelor,Organic,CMP04,-0.3185,-0.9865,0,0
731,CUST00605,2025-08-01,B13,62,5851.43,70200.80,11,40,17.22,7.82,2,0,19.5,1,13,5,1,6,8,Mobile,North,Dark,PhD,Organic,CMP02,-0.3049,-0.4817,1,0
999,CUST00605,2025-08-01,B13,62,5851.43,70200.80,11,40,17.22,7.82,2,0,19.5,1,13,5,1,6,8,Mobile,North,Dark,PhD,Organic,CMP02,-0.3049,-0.4817,1,0
5180,CUST00634,2026-01-01,B04,49,5360.73,64293.39,3,7,4.85,13.97,1,1,24.1,2,9,3,1,6,19,Mobile,Central,Dark,Master,Affiliate,CMP01,0.5543,0.4336,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4487,CUST04688,2026-03-01,B18,50,7126.75,85093.47,7,22,19.68,15.36,0,0,2.3,3,5,2,2,6,17,Mobile,South,Light,Master,Organic,CMP03,0.6013,-0.7086,1,1
1108,CUST04925,2025-12-01,B09,50,2436.57,29379.14,6,18,19.08,7.97,0,0,74.9,2,7,6,1,6,11,Tablet,East,System,Master,Organic,CMP16,-0.9709,0.8562,0,0
2390,CUST04925,2025-12-01,B09,50,2436.57,29379.14,6,18,19.08,7.97,0,0,74.9,2,7,6,1,6,11,Tablet,East,System,Master,Organic,CMP16,-0.9709,0.8562,0,0
478,CUST05114,2025-01-01,B23,34,6543.33,78517.32,10,30,22.51,24.51,0,0,33.1,0,10,2,1,9,19,Desktop,West,Light,Master,Referral,CMP05,-2.1487,-0.6810,1,1
1242,CUST05114,2025-01-01,B23,34,6543.33,78517.32,10,30,22.51,24.51,0,0,33.1,0,10,2,1,9,19,Desktop,West,Light,Master,Referral,CMP05,-2.1487,-0.6810,1,1

they are exact duplicated columns, I will drop them

In [16]:
df_clean = df.drop_duplicates()

In [17]:
df_clean.shape

(7484, 29)

#### Repeated entities

In [36]:
customer_counts = df_clean['customer_id'].value_counts()
customer_counts.head()

customer_id
CUST03090    3
CUST02133    3
CUST01676    3
CUST03203    3
CUST02897    3
Name: count, dtype: int64

In [40]:
repeated_customers = customer_counts[customer_counts > 1]
len(repeated_customers)

1775

In [43]:
df_clean[df_clean['customer_id'].isin(repeated_customers.index)].sort_values(by='customer_id')

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
630,CUST00001,2025-12-01,B17,40,14331.28,172408.24,6,21,32.13,10.34,1,0,8.2,2,12,4,1,5,8,Mobile,South,Dark,Master,Search,CMP01,0.4028,-0.3411,1,0
4953,CUST00001,2025-11-01,B17,40,14525.17,173291.39,9,31,23.24,10.14,1,0,47.9,1,13,4,3,7,18,Mobile,South,Dark,Master,Partner_Rare,CMP02,1.4404,0.7305,1,0
4195,CUST00003,2026-04-01,B15,31,2283.80,27365.68,7,24,31.83,11.54,1,0,44.1,2,9,6,1,6,11,Mobile,North,Light,High School,Social,CMP06,2.5045,-0.0049,0,0
6624,CUST00003,2026-05-01,B15,31,2359.29,28074.30,7,23,33.04,7.09,2,0,50.2,0,5,3,0,5,19,Mobile,North,Light,High School,Search,CMP01,-0.2593,-0.6711,1,0
3236,CUST00004,2026-02-01,B15,27,4735.69,56815.43,9,33,43.15,23.18,0,0,15.4,3,13,8,1,6,11,Mobile,North,Dark,Bachelor,Referral,CMP01,1.1225,-0.0007,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4725,CUST05196,2026-01-01,B17,33,3534.45,42973.21,4,18,4.43,16.47,1,0,48.5,1,5,6,1,4,22,Tablet,South,System,Bachelor,Email,CMP02,1.6201,-0.5727,0,0
3032,CUST05196,2025-12-01,B17,33,3425.38,41673.18,2,11,14.20,10.94,0,0,41.3,1,11,4,0,8,22,Tablet,South,System,Bachelor,Organic,CMP02,-2.1248,-0.6968,0,0
58,CUST05196,2026-02-01,B17,33,3487.03,42174.26,9,27,31.47,12.64,3,0,37.9,1,10,5,3,6,17,Tablet,South,System,Bachelor,Search,CMP02,-0.2453,0.5787,0,0
3802,CUST05199,2026-05-01,B18,55,4920.51,59454.57,8,26,36.64,20.40,2,0,23.6,2,13,4,0,7,10,Desktop,South,Dark,Bachelor,Email,CMP02,-1.1635,0.8358,1,1
3290,CUST05199,2026-06-01,B18,55,4633.05,55433.03,6,20,20.60,4.15,3,0,51.8,1,4,2,0,5,9,Desktop,South,Dark,Bachelor,Organic,CMP01,0.8253,-0.7780,1,0

In [28]:
len(repeated_customers)

1775

In [29]:
customer_counts.value_counts().sort_values()

count
3     509
2    1266
1    3425
Name: count, dtype: int64

In [31]:
df_clean[
    df_clean['customer_id'] == 'CUST03090'
][
    [
        'customer_id',
        'observation_month',
        'monthly_income',
        'purchased'
    ]
].sort_values('observation_month')

     customer_id observation_month  monthly_income  purchased
6319   CUST03090        2025-10-01         3390.37          1
1      CUST03090        2025-11-01         3313.13          0
2837   CUST03090        2025-12-01         3529.16          1

they are not duplicated rows, they are legitimate repeated measurements.
same customers with different time points