In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("lln_practice_dataset.csv")
df.head()

,customer_id,customer_spend,purchased,treatment,converted,y_true,y_pred
0,1,58.7802,0,1,0,1,1
1,2,42.6029,1,1,1,1,1
2,3,40.4541,0,1,0,1,1
3,4,40.4544,0,1,0,1,1
4,5,94.9764,0,0,1,0,0

In [4]:
df.shape

(100000, 7)

## LLN

In [9]:
population_customer_spend = df['customer_spend']
population_mean = population_customer_spend.mean()
population_mean

np.float64(50.078228267)

In [8]:
n_values = [10, 50, 100, 500, 1000, 5000, 10000]

def sample_mean_calculator(n, population):
    sample_means = pd.DataFrame(columns=['n', 'sample_mean'])
    for n in n_values:
        sample = population.sample(
            n=n,
            replace = True
        )
        sample_mean = sample.mean()
        sample_means.loc[len(sample_means)] = [n, sample_mean]
    return sample_means

In [10]:
sample_means_df = sample_mean_calculator(n_values, population_customer_spend)
sample_means_df

         n  sample_mean
0     10.0    47.257740
1     50.0    47.346666
2    100.0    53.916148
3    500.0    50.234258
4   1000.0    51.039728
5   5000.0    49.392365
6  10000.0    50.105222

here we can oberve that as n increase, the sample mean converges the population mean